import ast
import re
import time

from app.tools.base import Tool


class EchoTool(Tool):
    name = "echo"

    def run(self, input_text: str) -> str:
        return input_text


class MathTool(Tool):
    name = "math"

    def run(self, input_text: str) -> str:
        nums = [float(match) for match in re.findall(r"-?\d+(?:\.\d+)?", input_text)]
        if not nums:
            return "No numeric values found."
        return f"sum={sum(nums)}"


class SlowEchoTool(Tool):
    name = "slow_echo"

    def run(self, input_text: str) -> str:
        time.sleep(0.2)
        return f"slow:{input_text}"


class FlakyTool(Tool):
    name = "flaky"

    def __init__(self) -> None:
        self._attempts: dict[str, int] = {}

    def run(self, input_text: str) -> str:
        attempt = self._attempts.get(input_text, 0) + 1
        self._attempts[input_text] = attempt
        if attempt == 1:
            raise RuntimeError("transient_failure")
        return f"recovered:{input_text}"


class SensitiveEchoTool(Tool):
    name = "sensitive_echo"

    def run(self, input_text: str) -> str:
        return f"approved:{input_text}"


# ---------------------------------------------------------------------------
# Search Tool — simulates a knowledge-base lookup for demo purposes.
# In a production deployment this would call a real search API or vector DB.
# ---------------------------------------------------------------------------

_SEARCH_CORPUS: dict[str, str] = {
    "ai": "AI systems automate complex decisions via machine learning, neural networks, and agent orchestration.",
    "observability": "Observability surfaces system behaviour through structured logs, metrics, distributed traces, and alerts.",
    "workflow": "Workflow orchestration coordinates multi-step processes across agents, tools, and data sources.",
    "vendor": "Leading AI platform vendors include Anthropic, OpenAI, Cohere, Mistral, and open-source alternatives.",
    "pricing": "AI API pricing is typically token-based. Batch inference reduces cost by 40–70% vs. real-time endpoints.",
    "incident": "Incident management workflows capture alerts, triage severity, assign owners, and track resolution SLAs.",
    "rollout": "Phased rollouts reduce risk: canary → staging → production with automated rollback on error-rate breaches.",
    "metrics": "Key platform metrics: p95 latency, error rate, step-completion rate, retry rate, and cost-per-run.",
    "risk": "Common risk factors: data-quality drift, tool timeouts, model hallucination, and insufficient human review.",
    "recommendation": "Recommendations are generated by the reviewer agent after comparing multi-criteria scores and traces.",
}


class SearchTool(Tool):
    """Keyword-based search against a built-in corpus (demo-safe, no external calls)."""

    name = "search"

    def run(self, input_text: str) -> str:
        tokens = [t.lower().strip(".,;:?!") for t in input_text.split()]
        for token in tokens:
            for key, snippet in _SEARCH_CORPUS.items():
                if key in token or token in key:
                    return f'search_result: "{snippet}"'
        return (
            f'search_result: No specific entry for "{input_text}". '
            "Consider narrowing the query to a single topic."
        )


# ---------------------------------------------------------------------------
# HTTP Request Tool — simulates an outbound API call for demo purposes.
# Whitelisted mock endpoints return canned JSON payloads.
# ---------------------------------------------------------------------------

_HTTP_MOCK_RESPONSES: dict[str, str] = {
    "api/kpi": '{"revenue_growth": 12.4, "churn_rate": 2.1, "nps": 67}',
    "api/incidents": '{"total": 30, "p1": 2, "p2": 11, "resolved": 27}',
    "api/health": '{"status": "healthy", "latency_ms": 42}',
    "api/config": '{"feature_flags": {"new_planner": true, "parallel_exec": true}}',
}


class HttpRequestTool(Tool):
    """Simulated HTTP GET tool for demo API integrations (no real network calls)."""

    name = "http_request"

    def run(self, input_text: str) -> str:
        path = input_text.strip().lower().lstrip("/")
        for key, payload in _HTTP_MOCK_RESPONSES.items():
            if key in path:
                return f"http_200: {payload}"
        return f'http_404: No mock endpoint registered for "{input_text}". Register it in HttpRequestTool._HTTP_MOCK_RESPONSES.'


# ---------------------------------------------------------------------------
# Code Execution Tool — evaluates safe arithmetic expressions only.
# Arbitrary code execution is intentionally blocked.
# ---------------------------------------------------------------------------

# Allowed AST node types for arithmetic-only evaluation.
_ALLOWED_AST_NODES = (
    ast.Expression,
    ast.BinOp,
    ast.UnaryOp,
    ast.Num,       # Python < 3.8 number literal
    ast.Constant,  # Python ≥ 3.8 literal
    ast.Add, ast.Sub, ast.Mult, ast.Div, ast.FloorDiv, ast.Mod, ast.Pow,
    ast.UAdd, ast.USub,
)


def _validate_ast(tree: ast.AST) -> None:
    """Raise ValueError if the tree contains any non-arithmetic nodes."""
    for node in ast.walk(tree):
        if not isinstance(node, _ALLOWED_AST_NODES):
            raise ValueError(f"Disallowed expression node: {type(node).__name__}")

class CodeExecTool(Tool):
    """Evaluates simple arithmetic expressions in a sandboxed context."""

    name = "code_exec"

    # Only digits, basic operators, parentheses, spaces, and dots are allowed.
    _SAFE_PATTERN = re.compile(r"^[\d+\-*/().\s]+$")

    def run(self, input_text: str) -> str:
        expr = input_text.strip()
        if not self._SAFE_PATTERN.match(expr):
            return f'code_exec_error: Expression "{expr}" contains disallowed characters. Only arithmetic is permitted.'
        try:
            # ast.literal_eval handles simple literals; for arithmetic we first
            # compile and check the AST, then evaluate only with numeric ops.
            tree = ast.parse(expr, mode="eval")
            _validate_ast(tree)
            result = eval(ast.compile(tree, filename="<arithmetic>", mode="eval"), {"__builtins__": {}}, {})  # noqa: S307
            return f"code_exec_result={result}"
        except (ValueError, TypeError, SyntaxError) as exc:
            return f"code_exec_error: {exc}"
